### PR TITLE
Change an unescape() call to unquote(), as unescape doesn't exists an…

### PR DESCRIPTION
**Pull request by original-birdman**
…d unquote is the correct thing to do.

### CODE REVIEW

**Comment by original-birdman** [comment]
Forcing in a web call taht gets to this code shows that unescape isn't defined.
```
File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 190, in process
File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 241, in render
File "/home/vixdev/5.0/builds/openvix/developer/inihdx/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-1+gitAUTOINC+260e23ee18-r1/git/plugin/controllers/base.py", line 123, in render
File "/home/vixdev/5.0/builds/openvix/developer/inihdx/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-1+gitAUTOINC+260e23ee18-r1/git/plugin/controllers/web.py", line 997, in P_tvbrowser
File "/home/vixdev/5.0/builds/openvix/developer/inihdx/tmp/work/all-oe-linux/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-1+gitAUTOINC+260e23ee18-r1/git/plugin/controllers/models/timers.py", line 510, in tvbrowser
    
exceptions.NameError: global name 'unescape' is not defined
```

**Comment by jbleyel** [comment]
I have fixed the master.

**Comment by jbleyel** [comment]
Please close this pull request.

**Comment by original-birdman** [comment]
OK. have closed.

Does this mean it will get the Theme as well? Just that I have a few other bug fixes coming along...

**Comment by Schimmelreiter** [comment]
Create pull requests directly against master:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif

It will speed up merges drastically.

**Comment by original-birdman** [comment]
The next PR I wish to submit makes no sense against master.
It's for `services.py`, which hasn't changed in master for >4 years and there are many differences.

**Pull request closed without merging**
