### PR TITLE
fix tstrings [settings.tmpl]

### PR DESCRIPTION
**Pull request by thawtes**

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
Create pull on e2openPlugins

**Comment by thawtes** [comment]
how to ? 
pull on e2openPlugins not Theme branch ?

**Comment by thawtes** [comment]
:) ok ok thanks

**Comment by Schimmelreiter** [comment]
And there it is:
https://github.com/oe-alliance/e2openplugin-OpenWebif/commit/d40d58e000da4bd6b8e51972c221f1a098ad31ed
:)

I just want to pull in one direction only ... from upstream to us.

**Pull request closed without merging**
