### PR TITLE
Fix blue screen when you stream viaRemoteStreamConvert

### PR DESCRIPTION
**Pull request by javilonas**
This corrects the BSOD that occurs in the host server from a client to zap receiver using the plugin RemoteStreamConvert

### CODE REVIEW

**Comment by Schimmelreiter** [comment]
please send a pull request for the e2openplugins Version instead. Will then merge it to here too.

**Comment by Schimmelreiter** [comment]
Until someone comes up with a better solution we will take this one.

**Comment by RobvanderDoes** [comment]
1- How can you possibly expect any solution at all, let alone a better one, if there is no decent (reproducible) bug-description.
2- This only hides the issue, making it even more unlikely that the cause will ever be found and fixed.
3- This makes the functionality only bulkier, slower and harder to read. 
4- In all the years the plugin has been available,  I never read about any such issue.

All in all: I suggest to follow the original plugin and revert this 'fix'. The the originator of the pullrequest has all the time to give more insight in his problem.

**Comment by RobvanderDoes** [comment]
No comments, so I take it there's no objection against reverting this not needed 'fix'..

**Pull request merged**
