### PR TITLE
Fix missing import or unquote from urllib

### PR DESCRIPTION
**Pull request by original-birdman**
Without this you'll get a crash

### CODE REVIEW

**Comment by jbleyel** [comment]
No pull requests here please.
I have fix this in the master.

**Comment by AbuBaniaz** [comment]
Is the theme branch of the OE-A fork exactly the same as the master branch of the e2openplugin version?

**Comment by original-birdman** [comment]
As long as it's been fixed (which it now is) I don't mind how it got there.

**Comment by Schimmelreiter** [comment]
Two things are different:

1. All images and owibranding.py have been deleted
The images are in oe-alliance-branding and owibranding.py is actually just a poor man's (= PLi/VTi **g**)  rewrite of oe-alliance-branding
2. transcoding.py differs as the transcoding setup differs between VTi on the one side and oe-a on the other.

All other files are identical.

**Pull request closed without merging**
